server:
  port: 8006

spring:
  profiles:
    active: dev
  application:
    name: service-oss

#mybatis:
#  type-aliases-package: com.example.demo.pojo
#  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ #注册到哪里这里是eureka注册中心的地址7001
  instance:
    instance-id: service-oss

#配置阿里云oss常量
aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    keyid: LTAI5t7QV4VtCJ4MDssskB7f
    keysecret: pwUKsmk9a8cQ5nZ8rSFoENm3ig8Qxa
    bucketname: cloud-ink