server:
  port: 8009

spring:
  application:
    name: alipay-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: pay-service

aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    keyid: LTAI5tLvNZsssaBPvKknV7rGsXJY
    keysecret: dwcsJQBeSCzdj2jGrDbeBKWrEjtANy
    bucketname: cloud-ink